In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [2]:
df_orders=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\orders_clean.csv")
df_products=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\products_clean.csv")
df_order_items=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\order_items_clean.csv")
df_payment=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\payment_clean.csv")
df_customers=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\customers_clean.csv")
df_reviews=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\reviews_clean.csv")
df_sellers=pd.read_csv(r"C:\Users\SAMA\Documents\Brazilian E-Commerce\2_Cleaned Data\sellers_clean.csv")

In [3]:
final_data=df_orders.merge(df_order_items,how='left',on='order_id')

In [5]:
final_data

,Unnamed: 0_x,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_time_hours,delivery_time_days,delivery_delay_days,Unnamed: 0_y,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_cost
0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,0.183333,8.0,-8.0,100785.0,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,10/6/2017 11:07,29.99,8.72,38.71
1,1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,30.716667,13.0,-6.0,36896.0,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,7/30/2018 3:24,118.70,22.76,141.46
2,2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,0.283333,9.0,-18.0,31504.0,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,8/13/2018 8:55,159.90,19.22,179.12
3,3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,0.283333,13.0,-13.0,65021.0,1.0,d0b61bfb1de832b15ba9d266ca96e5b0,66922902710d126a0e7d26b0e3805106,11/23/2017 19:45,45.00,27.20,72.20
4,4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,1.033333,2.0,-10.0,76043.0,1.0,65266b2da20d04dbe00c5c2d3bb7859e,2c9e548be18521d1c43cde1c582c6de8,2/19/2018 20:31,19.90,8.72,28.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110908,99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,0.200000,22.0,-2.0,43826.0,1.0,f1d4ce8c6dd66c47bbaa8c6781c2a923,1f9ab4708f3056ede07124aad39a2554,2/12/2018 13:10,174.90,20.10,195.00
110909,99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,0.300000,24.0,-6.0,57884.0,1.0,b80910977a37536adeddd63663f916ad,d50d79cb34e38265a8649c383dcffd48,9/5/2017 15:04,205.99,65.02,271.01
110910,99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,17.0,-21.0,7844.0,1.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,1/12/2018 21:36,179.99,40.59,220.58
110911,99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,17.0,-21.0,7845.0,2.0,d1c427060a0f73f6b889a5c7c61f2ac4,a1043bafd471dff536d0c462352beb48,1/12/2018 21:36,179.99,40.59,220.58
110912,99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,14.383333,7.0,-18.0,45266.0,1.0,006619bbed68b000c8ba3f8725d5409e,ececbfcff9804a2d6b40f589df8eef2b,3/15/2018 10:55,68.50,18.36,86.86

In [6]:
final_data=final_data.merge(df_products,how='left',on='product_id')

In [8]:
final_data

,Unnamed: 0_x,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_time_hours,...,total_cost,Unnamed: 0,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,0.183333,...,38.71,2349.0,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0
1,1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,30.716667,...,141.46,20550.0,perfumaria,29.0,178.0,1.0,400.0,19.0,13.0,19.0
2,2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,0.283333,...,179.12,12228.0,automotivo,46.0,232.0,1.0,420.0,24.0,19.0,21.0
3,3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,0.283333,...,72.20,29925.0,pet_shop,59.0,468.0,3.0,450.0,30.0,10.0,20.0
4,4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,1.033333,...,28.62,11900.0,papelaria,38.0,316.0,4.0,250.0,51.0,15.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110908,99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,0.200000,...,195.00,1778.0,bebes,52.0,828.0,4.0,4950.0,40.0,10.0,40.0
110909,99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,0.300000,...,271.01,14953.0,eletrodomesticos_2,51.0,500.0,2.0,13300.0,32.0,90.0,22.0
110910,99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,...,220.58,8290.0,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
110911,99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,...,220.58,8290.0,informatica_acessorios,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0
110912,99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,14.383333,...,86.86,19887.0,beleza_saude,45.0,569.0,1.0,150.0,16.0,7.0,15.0

In [10]:
final_data = final_data.loc[:, ~final_data.columns.str.contains('^Unnamed')]
df_sellers = df_sellers.loc[:, ~df_sellers.columns.str.contains('^Unnamed')]

In [11]:
final_data=final_data.merge(df_sellers,how='left',on='seller_id')

In [12]:
final_data

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_time_hours,delivery_time_days,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,0.183333,8.0,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,30.716667,13.0,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,0.283333,9.0,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,0.283333,13.0,...,59.0,468.0,3.0,450.0,30.0,10.0,20.0,31842.0,belo horizonte,MG
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,1.033333,2.0,...,38.0,316.0,4.0,250.0,51.0,15.0,15.0,8752.0,mogi das cruzes,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110908,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,0.200000,22.0,...,52.0,828.0,4.0,4950.0,40.0,10.0,40.0,17602.0,tupa,SP
110909,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,0.300000,24.0,...,51.0,500.0,2.0,13300.0,32.0,90.0,22.0,8290.0,sao paulo,SP
110910,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,17.0,...,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG
110911,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,17.0,...,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,37175.0,ilicinea,MG
110912,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,14.383333,7.0,...,45.0,569.0,1.0,150.0,16.0,7.0,15.0,14407.0,franca,SP

In [13]:
final_data = final_data.merge(df_payment, on='order_id', how='left')

final_data = final_data.merge(df_reviews, on='order_id', how='left')

final_data = final_data.merge(df_customers, on='customer_id', how='left')

In [14]:
final_data

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,approval_time_hours,delivery_time_days,...,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,Unnamed: 0,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,0.183333,8.0,...,4.0,2017-10-11 00:00:00,"Não testei o produto ainda, mas ele veio corre...",10/11/2017 0:00,2017-10-12 03:43:00,70296,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,0.183333,8.0,...,4.0,2017-10-11 00:00:00,"Não testei o produto ainda, mas ele veio corre...",10/11/2017 0:00,2017-10-12 03:43:00,70296,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,0.183333,8.0,...,4.0,2017-10-11 00:00:00,"Não testei o produto ainda, mas ele veio corre...",10/11/2017 0:00,2017-10-12 03:43:00,70296,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,30.716667,13.0,...,4.0,2018-08-08 00:00:00,Muito bom o produto.,8/8/2018 0:00,2018-08-08 18:37:00,77027,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,0.283333,9.0,...,5.0,2018-08-18 00:00:00,NaN,8/18/2018 0:00,2018-08-22 19:07:00,554,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116483,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,0.200000,22.0,...,4.0,2018-03-01 00:00:00,So uma peça que veio rachado mas tudo bem rs,3/1/2018 0:00,2018-03-02 17:50:00,78424,da62f9e57a76d978d02ab5362c509660,11722,praia grande,SP
116484,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,0.300000,24.0,...,5.0,2017-09-22 00:00:00,Foi entregue antes do prazo.,9/22/2017 0:00,2017-09-22 23:10:00,19901,737520a9aad80b3fbbdad19b66b37b30,45920,nova vicosa,BA
116485,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,17.0,...,2.0,2018-01-26 00:00:00,Foi entregue somente 1. Quero saber do outro p...,1/26/2018 0:00,2018-01-27 09:16:00,16923,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ
116486,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,0.133333,17.0,...,2.0,2018-01-26 00:00:00,Foi entregue somente 1. Quero saber do outro p...,1/26/2018 0:00,2018-01-27 09:16:00,16923,5097a5312c8b157bb7be58ae360ef43c,28685,japuiba,RJ
116487,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,14.383333,7.0,...,5.0,2018-03-17 00:00:00,NaN,3/17/2018 0:00,2018-03-17 16:33:00,38125,60350aa974b26ff12caad89e55993bd6,83750,lapa,PR

In [15]:
final_data.shape

(116488, 46)

In [16]:
final_data.isna().sum().sort_values(ascending=False)

review_comment_message           67857
delivery_time_days                1330
delivery_delay_days               1330
order_delivered_customer_date     1330
review_score                       955
review_answer_timestamp            955
Unnamed: 0_y                       955
review_creation_date               955
review_id                          955
review_comment_title               955
product_width_cm                    21
product_weight_g                    21
product_height_cm                   21
product_length_cm                   21
Unnamed: 0_x                         3
payment_installments                 3
payment_type                         3
payment_value                        3
payment_sequential                   3
seller_state                         1
seller_zip_code_prefix               1
seller_city                          1
product_id                           1
seller_id                            1
order_item_id                        1
total_cost                           1
product_category_name                1
product_name_lenght                  1
product_description_lenght           1
product_photos_qty                   1
price                                1
freight_value                        1
shipping_limit_date                  1
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                    0
order_delivered_carrier_date         0
order_estimated_delivery_date        0
approval_time_hours                  0
order_id                             0
Unnamed: 0                           0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
dtype: int64

In [17]:
final_data.duplicated().sum()

np.int64(0)

In [18]:
final_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 116488 entries, 0 to 116487
Data columns (total 46 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       116488 non-null  str
 1   customer_id                    116488 non-null  str
 2   order_status                   116488 non-null  str
 3   order_purchase_timestamp       116488 non-null  str
 4   order_approved_at              116488 non-null  str
 5   order_delivered_carrier_date   116488 non-null  str
 6   order_delivered_customer_date  115158 non-null  str
 7   order_estimated_delivery_date  116488 non-null  str
 8   approval_time_hours            116488 non-null  float64
 9   delivery_time_days             115158 non-null  float64
 10  delivery_delay_days            115158 non-null  float64
 11  order_item_id                  116487 non-null  float64
 12  product_id                     116487 non-null  str
 13  seller_id                      116487 non-null  str
 14  shipping_limit_date            116487 non-null  str
 15  price                          116487 non-null  float64
 16  freight_value                  116487 non-null  float64
 17  total_cost                     116487 non-null  float64
 18  product_category_name          116487 non-null  str
 19  product_name_lenght            116487 non-null  str
 20  product_description_lenght     116487 non-null  str
 21  product_photos_qty             116487 non-null  float64
 22  product_weight_g               116467 non-null  float64
 23  product_length_cm              116467 non-null  float64
 24  product_height_cm              116467 non-null  float64
 25  product_width_cm               116467 non-null  float64
 26  seller_zip_code_prefix         116487 non-null  float64
 27  seller_city                    116487 non-null  str
 28  seller_state                   116487 non-null  str
 29  Unnamed: 0_x                   116485 non-null  float64
 30  payment_sequential             116485 non-null  float64
 31  payment_type                   116485 non-null  str
 32  payment_installments           116485 non-null  float64
 33  payment_value                  116485 non-null  float64
 34  Unnamed: 0_y                   115533 non-null  float64
 35  review_id                      115533 non-null  str
 36  review_score                   115533 non-null  float64
 37  review_comment_title           115533 non-null  str
 38  review_comment_message         48631 non-null   str
 39  review_creation_date           115533 non-null  str
 40  review_answer_timestamp        115533 non-null  str
 41  Unnamed: 0                     116488 non-null  int64
 42  customer_unique_id             116488 non-null  str
 43  customer_zip_code_prefix       116488 non-null  int64
 44  customer_city                  116488 non-null  str
 45  customer_state                 116488 non-null  str
dtypes: float64(19), int64(2), str(25)
memory usage: 90.2 MB

In [19]:
final_data = final_data.loc[:, ~final_data.columns.str.contains('^Unnamed')]

In [20]:
final_data.to_csv('final_dataset.csv', index=False)