In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [2]:
df=pd.read_csv(r"C:\Users\SAMA\Documents\Olist\olist_order_items_dataset.csv")

In [3]:
df

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,5/3/2017 11:05,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,1/18/2018 14:48,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,8/15/2018 10:10,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2/13/2017 13:57,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,5/2/2018 4:11,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,7/20/2018 4:31,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,10/30/2017 17:14,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,8/21/2017 0:04,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,6/12/2018 17:10,43.00,12.79

In [4]:
df_cleaned=df.copy()

In [5]:
df_cleaned.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [6]:
df_cleaned['total_cost']=df_cleaned['price']+df_cleaned['freight_value']

In [7]:
df_cleaned

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_cost
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,9/19/2017 9:45,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,5/3/2017 11:05,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,1/18/2018 14:48,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,8/15/2018 10:10,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2/13/2017 13:57,199.90,18.14,218.04
...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,5/2/2018 4:11,299.99,43.41,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,7/20/2018 4:31,350.00,36.53,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,10/30/2017 17:14,99.90,16.95,116.85
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,8/21/2017 0:04,55.99,8.72,64.71
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,6/12/2018 17:10,43.00,12.79,55.79

In [8]:
df_cleaned['total_cost'].sum()

np.float64(15843553.24)

In [9]:
df_cleaned['items_count']=df_cleaned.groupby('order_id')['order_item_id'].transform('count')

In [10]:
df_cleaned.drop('items_count',axis=1,inplace=True)

In [11]:
df_cleaned.sample(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_cost
68091,9ba4f1229c25da86b79e5f8af0e56461,2,17c4bd4269902c84acc14c497f282ddb,75d34ebb1bd0bd7dde40dd507b8169c3,4/14/2017 10:22,299.99,12.71,312.70
24995,38df543e1956e91a0b4ee89c4a49dbf3,1,19c91ef95d509ea33eda93495c4d3481,06a2c3af7b3aee5d69171b0e14f0ee87,5/15/2018 11:55,119.99,18.82,138.81
44523,652dd1e43c57c5f82622cd0d4ec1c376,1,44493ebe02de3fd58d529f40fd2944d1,f8db351d8c4c4c22c6835c19a46f01b0,8/6/2018 5:05,29.90,19.40,49.30
28857,41a75aec932b24ba50e98ba8b50b625d,1,dcb7642f668e09b75d526454940124b9,92eb0f42c21942b6552362b9b114707d,3/6/2018 8:30,18.07,2.15,20.22
97503,dd372e737332ef27597292546559253a,1,5ab02ca028398131a5ae91401eb49788,80e6699fe29150b372a0c8a1ebf7dcc8,5/5/2017 11:03,39.99,16.05,56.04
79035,b3c763d35ce46cf0a205b217814323ee,1,9e24c718d40f018498c6b5db74bf9dc9,612170e34b97004b3ba37eae81836b4c,8/16/2018 13:15,239.90,28.96,268.86
91422,cf70b7c4ec0170d19ee4259edded4b00,1,661d83b6b4988942aa9b449b57e12f81,46dc3b2cc0980fb8ec44634e21d2718e,10/5/2017 2:14,129.99,17.35,147.34
71910,a4086a85cd42acc124fd2ffe7ae22fd3,1,bc74f63361c15c1a5baa5b97ac432e62,4869f7a5dfa277a7dca6462dcf3b52b2,3/19/2018 15:35,239.00,14.11,253.11
65969,96c833757e09a989bb5c13d0470d7f2a,1,ebe8bbf509715e46f138ac98b1cbb12e,4a3ccda38b2129705f3fb522db62ca31,4/12/2018 9:35,65.90,18.34,84.24
56492,80848ca638a6e695838ebee7d2409893,2,e85fbac9d80b832ba812bc5d7ffe236d,1f50f920176fa81dab994f9023523100,5/2/2018 9:55,38.90,19.32,58.22

In [12]:
df_cleaned[['price','freight_value']].describe()

               price  freight_value
count  112650.000000  112650.000000
mean      120.653739      19.990320
std       183.633928      15.806405
min         0.850000       0.000000
25%        39.900000      13.080000
50%        74.990000      16.260000
75%       134.900000      21.150000
max      6735.000000     409.680000

In [13]:
df_cleaned['price'].quantile([0.5, 0.9, 0.95, 0.99])

0.50     74.99
0.90    229.80
0.95    349.90
0.99    890.00
Name: price, dtype: float64

In [14]:
df_cleaned.to_csv('order_items_clean.csv')